# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07f2c831423b3c181a88f8acff8dc546732950d60e0a71feed26ed0ec4e86ef8157d4d9aa8d46c81f30d6c08ca05983b73680cf2ed23afc8fdaf9ae7b08c1b8d

test:
  secret_key_base: 4ad3a200105a23c88e018e803a72651a60b3c6a5871389d4240e739ba0cc3aa5cd82be0ea13b57f9bcdb07ae65acc7f0ea6755db7bccd8e7b9fc672a8cc42d70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
